[book]
authors = ["314ShadePi"]
language = "en"
multilingual = false
src = "src"
title = "Game Mechanics"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/314ShadePi/game-mechanics"
edit-url-template = "https://github.com/314ShadePi/game-mechanics/edit/main/{path}"
